In [ ]:
#1
import numpy as np

Xn = -3.5
dX = 1.5
Xk = 4.5
X = np.arange(Xn, Xk + dX, dX)
print("X =", X)

Y = np.sin(X / 2)
print("Y =", Y)

A = np.arange(0, 6)
print("A =", A)

ans = A / 2 + np.pi
print("ans =", ans)

X = [-3.5 -2.  -0.5  1.   2.5  4.   5.5]
Y = [-0.98398595 -0.84147098 -0.24740396  0.47942554  0.94898462  0.90929743
  0.38166099]
A = [0 1 2 3 4 5]
ans = [3.14159265 3.64159265 4.14159265 4.64159265 5.14159265 5.64159265]


In [4]:
#2
V = np.array([1, 2, 3, 4, 5])
print("V =", V)

W = np.array([1.1, 2.3, -0.1, 5.88])
print("W =", W)

V = [1 2 3 4 5]
W = [ 1.1   2.3  -0.1   5.88]


In [6]:
#3
X = np.array([[1], [2], [3]])
print("X =")
print(X)

X =
[[1]
 [2]
 [3]]


In [7]:
#4
W = np.array([1.1, 2.3, -0.1, 5.88])
result = W[0] + 2 * W[2]  # W(1) + 2 * W(3)
print("result =", result)

result = 0.9000000000000001


In [8]:
#5
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("A =")
print(A)

result = A[0, 1] ** A[1, 1] / A[2, 2]  # A(1,2)^A(2,2)/A(3,3)
print("result =", result)

A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
result = 3.5555555555555554


In [9]:
#6
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
V = np.hstack((v1, v2, v3))  # Горизонтальная конкатенация
print("V =", V)

V = np.vstack((v1, v2, v3))  # Вертикальная конкатенация
print("V =")
print(V)

M = np.hstack((V, V, V))  # Горизонтальная конкатенация
print("M =")
print(M)

M = np.vstack((V, V))  # Вертикальная конкатенация
print("M =")
print(M)

V = [1 2 3 4 5 6 7 8 9]
V =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
M =
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]]
M =
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#7
A = np.array([[5, 7, 6, 5],
              [7, 10, 8, 7],
              [6, 8, 10, 9],
              [5, 7, 9, 10]])
print("A =")
print(A)

col2 = A[:, 1]
print("Второй столбец =", col2)

row3 = A[2, :]
print("Третья строка =", row3)

M = A[2:4, 1:3]
print("M =")
print(M)

A = np.delete(A, 1, axis=1)  # Удаление столбца с индексом 1
print("A после удаления второго столбца =")
print(A)

A = np.delete(A, 2, axis=0)  # Удаление строки с индексом 2
print("A после удаления третьей строки =")
print(A)

v = M.flatten()
print("v =", v)

b = v[1:4]
print("b =", b)

b = np.delete(b, 1)
print("b после удаления второго элемента =", b)

A =
[[ 5  7  6  5]
 [ 7 10  8  7]
 [ 6  8 10  9]
 [ 5  7  9 10]]
Второй столбец = [ 7 10  8  7]
Третья строка = [ 6  8 10  9]
M =
[[ 8 10]
 [ 7  9]]
A после удаления второго столбца =
[[ 5  6  5]
 [ 7  8  7]
 [ 6 10  9]
 [ 5  9 10]]
A после удаления третьей строки =
[[ 5  6  5]
 [ 7  8  7]
 [ 5  9 10]]
v = [ 8 10  7  9]
b = [10  7  9]
b после удаления второго элемента = [10  9]


In [12]:
#8
A = np.array([[1, 2, 0],
              [-1, 3, 1],
              [4, -2, 5]])

B = np.array([[-1, 0, 1],
              [2, 1, 1],
              [3, -1, -1]])

result = (A.T + B) ** 2 - 2 * A @ (0.5 * B.T - A)
print("Результат:")
print(result)

Результат:
[[ -1.  13.  28.]
 [ 14.  24.  24.]
 [ 60. -27.  53.]]


In [13]:
#9
x = np.array([0.1, -2.2, 3.14, 0, -1])

result = np.sin(x)
print("sin(x) =", result)

sin(x) = [ 0.09983342 -0.8084964   0.00159265  0.         -0.84147098]


In [14]:
#10
V = np.array([-1, 0, 3, -2, 1, -1, 1])

length = len(V)
print("Длина вектора V =", length)

Длина вектора V = 7


In [15]:
#11
V = np.array([1, 2, 3])

product = np.prod(V)
print("Произведение элементов вектора V =", product)

Произведение элементов вектора V = 6


In [16]:
#12
V = np.array([-1, 0, 3, -2, 1, -1, 1])

sum_elements = np.sum(V)
print("Сумма элементов вектора V =", sum_elements)

a = np.array([1, 2, 3])
b = np.array([2, 0, 1])
dot_product = np.sum(a * b)
print("Скалярное произведение векторов a и b =", dot_product)

Сумма элементов вектора V = 1
Скалярное произведение векторов a и b = 5


In [17]:
#13
V = np.array([-1, 0, 3, -2, 1, -1, 1])

min_element = np.min(V)
max_element = np.max(V)
print("Минимальный элемент вектора V =", min_element)
print("Максимальный элемент вектора V =", max_element)

Минимальный элемент вектора V = -2
Максимальный элемент вектора V = 3


In [18]:
#14
V = np.array([-1, 0, 3, -2, 1, -1, 1])

mean_value = np.mean(V)
print("Среднее арифметическое вектора V =", mean_value)

Среднее арифметическое вектора V = 0.14285714285714285


In [19]:
#14
V = np.array([-1, 0, 3, -2, 1, -1, 1])

sorted_V = np.sort(V)
print("Отсортированный вектор V =", sorted_V)

A = np.array([[3, 1, 2],
              [6, 4, 5],
              [9, 7, 8]])
sorted_A = np.sort(A, axis=0)
print("Отсортированная матрица A по столбцам:")
print(sorted_A)

Отсортированный вектор V = [-2 -1 -1  0  1  1  3]
Отсортированная матрица A по столбцам:
[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [20]:
#15
import numpy as np

b = np.array([2, 0, 1])
sorted_desc = -np.sort(-b)  # Сортировка по убыванию
sorted_asc = np.sort(b)     # Сортировка по возрастанию
print("Сортировка по убыванию:", sorted_desc)
print("Сортировка по возрастанию:", sorted_asc)

A = np.array([[1, 2, 0],
              [-1, 3, 1],
              [4, -2, 5]])
sorted_A = np.sort(A, axis=None).reshape(A.shape)  # Сортировка всей матрицы
print("Отсортированная матрица A:")
print(sorted_A)

Сортировка по убыванию: [2 1 0]
Сортировка по возрастанию: [0 1 2]
Отсортированная матрица A:
[[-2 -1  0]
 [ 1  1  2]
 [ 3  4  5]]


In [21]:
#16
I = np.eye(3, 3)
print("Единичная матрица 3x3:")
print(I)

I_col = np.eye(5, 1)
print("Единичная матрица 5x1:")
print(I_col)

Единичная матрица 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Единичная матрица 5x1:
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [22]:
#17
ones_matrix = np.ones((3, 2))
print("Матрица из единиц 3x2:")
print(ones_matrix)

Матрица из единиц 3x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
#18
zeros_matrix = np.zeros((3, 2))
print("Нулевая матрица 3x2:")
print(zeros_matrix)

Нулевая матрица 3x2:
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
#19
V = np.array([1, 2, 3])
diag_matrix = np.diag(V)  # Главная диагональ
print("Диагональная матрица (главная диагональ):")
print(diag_matrix)

diag_matrix_upper = np.diag(V, k=1)
print("Диагональная матрица (выше главной диагонали):")
print(diag_matrix_upper)

diag_matrix_lower = np.diag(V, k=-1)
print("Диагональная матрица (ниже главной диагонали):")
print(diag_matrix_lower)

# Извлечение главной диагонали матрицы
A = np.array([[-1, 2, 0],
              [2, 1, -1],
              [2, 1, 3]])
main_diag = np.diag(A)
print("Главная диагональ матрицы A:")
print(main_diag)

Диагональная матрица (главная диагональ):
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Диагональная матрица (выше главной диагонали):
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
Диагональная матрица (ниже главной диагонали):
[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]
Главная диагональ матрицы A:
[-1  1  3]


In [26]:
#20
random_matrix = np.random.rand(3, 3)
print("Случайная матрица 3x3:")
print(random_matrix)

random_tensor = np.random.rand(2, 2, 2)
print("Многомерный массив случайных чисел 2x2x2:")
print(random_tensor)

random_number = np.random.rand()
print("Одно случайное число:", random_number)


Случайная матрица 3x3:
[[0.46992423 0.76494621 0.41673519]
 [0.77092204 0.07822718 0.79914964]
 [0.2192351  0.33181873 0.21447227]]
Многомерный массив случайных чисел 2x2x2:
[[[0.26564209 0.31500183]
  [0.76288449 0.10503668]]

 [[0.01872674 0.94493264]
  [0.91278052 0.2603499 ]]]
Одно случайное число: 0.24297440336585774


In [27]:
#21
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

concat_cols = np.concatenate((A, B), axis=1)
print("Объединение по столбцам:")
print(concat_cols)

concat_rows = np.concatenate((A, B), axis=0)
print("Объединение по строкам:")
print(concat_rows)

Объединение по столбцам:
[[1 2 5 6]
 [3 4 7 8]]
Объединение по строкам:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
#22
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

lower_tri = np.tril(A)
print("Нижняя треугольная матрица:")
print(lower_tri)

lower_tri_k1 = np.tril(A, k=1)
print("Нижняя треугольная матрица (k=1):")
print(lower_tri_k1)

lower_tri_k2 = np.tril(A, k=-2)
print("Нижняя треугольная матрица (k=-2):")
print(lower_tri_k2)

Нижняя треугольная матрица:
[[1 0 0]
 [4 5 0]
 [7 8 9]]
Нижняя треугольная матрица (k=1):
[[1 2 0]
 [4 5 6]
 [7 8 9]]
Нижняя треугольная матрица (k=-2):
[[0 0 0]
 [0 0 0]
 [7 0 0]]


In [30]:
#23
upper_tri = np.triu(A)
print("Верхняя треугольная матрица:")
print(upper_tri)

upper_tri_k2 = np.triu(A, k=2)
print("Верхняя треугольная матрица (k=2):")
print(upper_tri_k2)

upper_tri_k1 = np.triu(A, k=-1)
print("Верхняя треугольная матрица (k=-1):")
print(upper_tri_k1)

Верхняя треугольная матрица:
[[1 2 3]
 [0 5 6]
 [0 0 9]]
Верхняя треугольная матрица (k=2):
[[0 0 3]
 [0 0 0]
 [0 0 0]]
Верхняя треугольная матрица (k=-1):
[[1 2 3]
 [4 5 6]
 [0 8 9]]


In [31]:
#24
A = np.array([[2, 4],
              [1, 3],
              [7, 9],
              [5, 8]])

size_A = A.shape
print("Размерность матрицы A:", size_A)

zeros_like_A = np.zeros_like(A)
print("Нулевая матрица того же размера, что и A:")
print(zeros_like_A)

V = np.array([2, 4, 6, 8, 1, 3, 5, 7])
ones_like_V = np.ones_like(V)
print("Единичный вектор того же размера, что и V:")
print(ones_like_V)

Размерность матрицы A: (4, 2)
Нулевая матрица того же размера, что и A:
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
Единичный вектор того же размера, что и V:
[1 1 1 1 1 1 1 1]


In [32]:
#25
A = np.array([[3, 2],
              [4, 3]])

det_A = np.linalg.det(A)
print("Определитель матрицы A:", det_A)

Определитель матрицы A: 1.0


In [33]:
#26
A = np.array([[1, 2, 3],
              [4, -2, 1],
              [7, 0, -1]])

trace_A = np.trace(A)
print("След матрицы A:", trace_A)

trace_alt = np.sum(np.diag(A))
print("След матрицы A (альтернативный способ):", trace_alt)

След матрицы A: -2
След матрицы A (альтернативный способ): -2


In [ ]:
#26
inv_A = np.linalg.inv(A)
print("Обратная матрица A:")
print(inv_A)

Обратная матрица A:
[[ 0.03030303  0.03030303  0.12121212]
 [ 0.16666667 -0.33333333  0.16666667]
 [ 0.21212121  0.21212121 -0.15151515]]


In [2]:
#27
import numpy as np
A = np.array([[2, 1, -5, 1],
              [1, -3, 0, -6],
              [0, 2, -1, 2],
              [1, 4, -7, 6]])

P = np.linalg.inv(A)
print("Обратная матрица P:")
print(P)

identity_matrix = np.dot(A, P)
print("Проверка A * P:")
print(identity_matrix)

Обратная матрица P:
[[ 1.33333333 -0.66666667  0.33333333 -1.        ]
 [-0.07407407  0.25925926  1.14814815 -0.11111111]
 [ 0.37037037 -0.2962963   0.25925926 -0.44444444]
 [ 0.25925926 -0.40740741 -0.51851852 -0.11111111]]
Проверка A * P:
[[ 1.00000000e+00 -5.55111512e-17  1.11022302e-16 -1.66533454e-16]
 [ 2.22044605e-16  1.00000000e+00 -2.22044605e-16 -1.11022302e-16]
 [-1.11022302e-16  2.22044605e-16  1.00000000e+00  2.77555756e-17]
 [ 0.00000000e+00  1.11022302e-16 -2.22044605e-16  1.00000000e+00]]


In [3]:
#28
#без решения
A = np.array([[1, 2, 3],
              [-2, -4, -6]])
b = np.array([5, 6])

try:
    x = np.linalg.lstsq(A, b, rcond=None)[0]  # метод наименьших квадратов
    print("Решение системы:")
    print(x)
except np.linalg.LinAlgError:
    print("Система не имеет решений.")

# с решением
A = np.array([[2, -1, 1],
              [3, 2, -5],
              [1, 3, -2]])
b = np.array([0, 1, 4])

x = np.linalg.solve(A, b)
print("Решение системы:")
print(x)

check = np.dot(A, x)
print("Проверка A * x:")
print(check)

Решение системы:
[-0.1 -0.2 -0.3]
Решение системы:
[0.46428571 1.67857143 0.75      ]
Проверка A * x:
[-2.22044605e-16  1.00000000e+00  4.00000000e+00]


In [ ]:
%pip install sympy

In [6]:
from scipy.linalg import lu

A = np.array([[3, -2, 1, 5],
              [6, -4, 2, 7],
              [9, -6, 3, 12]])

# Приведение матрицы к треугольной форме (LU-разложение)
P, L, U = lu(A)
print("Матрица P (перестановок):")
print(P)
print("Матрица L (нижняя треугольная):")
print(L)
print("Матрица U (верхняя треугольная):")
print(U)

# Приведение к ступенчатому виду (rref)
from sympy import Matrix

A_sympy = Matrix(A)
rref_matrix, _ = A_sympy.rref()
print("Матрица в ступенчатом виде (rref):")
print(rref_matrix)

Матрица P (перестановок):
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Матрица L (нижняя треугольная):
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.         1.        ]]
Матрица U (верхняя треугольная):
[[ 9. -6.  3. 12.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  1.]]
Матрица в ступенчатом виде (rref):
Matrix([[1, -2/3, 1/3, 0], [0, 0, 0, 1], [0, 0, 0, 0]])
